//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ObjectContextExampleModel", "FK_Entity_ChildEntity", "ChildEntity", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ObjectContextExample.ChildEntity), "Entity", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ObjectContextExample.Entity), true)]

#endregion

namespace ObjectContextExample
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ObjectContextExampleEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ObjectContextExampleEntities object using the connection string found in the 'ObjectContextExampleEntities' section of the application configuration file.
        /// </summary>
        public ObjectContextExampleEntities() : base("name=ObjectContextExampleEntities", "ObjectContextExampleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ObjectContextExampleEntities object.
        /// </summary>
        public ObjectContextExampleEntities(string connectionString) : base(connectionString, "ObjectContextExampleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ObjectContextExampleEntities object.
        /// </summary>
        public ObjectContextExampleEntities(EntityConnection connection) : base(connection, "ObjectContextExampleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ChildEntity> ChildEntities
        {
            get
            {
                if ((_ChildEntities == null))
                {
                    _ChildEntities = base.CreateObjectSet<ChildEntity>("ChildEntities");
                }
                return _ChildEntities;
            }
        }
        private ObjectSet<ChildEntity> _ChildEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Entity> Entities
        {
            get
            {
                if ((_Entities == null))
                {
                    _Entities = base.CreateObjectSet<Entity>("Entities");
                }
                return _Entities;
            }
        }
        private ObjectSet<Entity> _Entities;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ChildEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChildEntities(ChildEntity childEntity)
        {
            base.AddObject("ChildEntities", childEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Entities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntities(Entity entity)
        {
            base.AddObject("Entities", entity);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ObjectContextExampleModel", Name="ChildEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ChildEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ChildEntity object.
        /// </summary>
        /// <param name="childEntityID">Initial value of the ChildEntityID property.</param>
        public static ChildEntity CreateChildEntity(global::System.Int32 childEntityID)
        {
            ChildEntity childEntity = new ChildEntity();
            childEntity.ChildEntityID = childEntityID;
            return childEntity;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChildEntityID
        {
            get
            {
                return _ChildEntityID;
            }
            set
            {
                if (_ChildEntityID != value)
                {
                    OnChildEntityIDChanging(value);
                    ReportPropertyChanging("ChildEntityID");
                    _ChildEntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ChildEntityID");
                    OnChildEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _ChildEntityID;
        partial void OnChildEntityIDChanging(global::System.Int32 value);
        partial void OnChildEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ObjectContextExampleModel", "FK_Entity_ChildEntity", "Entity")]
        public EntityCollection<Entity> Entities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Entity>("ObjectContextExampleModel.FK_Entity_ChildEntity", "Entity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Entity>("ObjectContextExampleModel.FK_Entity_ChildEntity", "Entity", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ObjectContextExampleModel", Name="Entity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Entity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Entity object.
        /// </summary>
        /// <param name="entityID">Initial value of the EntityID property.</param>
        public static Entity CreateEntity(global::System.Int32 entityID)
        {
            Entity entity = new Entity();
            entity.EntityID = entityID;
            return entity;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EntityID
        {
            get
            {
                return _EntityID;
            }
            set
            {
                if (_EntityID != value)
                {
                    OnEntityIDChanging(value);
                    ReportPropertyChanging("EntityID");
                    _EntityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EntityID");
                    OnEntityIDChanged();
                }
            }
        }
        private global::System.Int32 _EntityID;
        partial void OnEntityIDChanging(global::System.Int32 value);
        partial void OnEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ChildEntityID
        {
            get
            {
                return _ChildEntityID;
            }
            set
            {
                OnChildEntityIDChanging(value);
                ReportPropertyChanging("ChildEntityID");
                _ChildEntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChildEntityID");
                OnChildEntityIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ChildEntityID;
        partial void OnChildEntityIDChanging(Nullable<global::System.Int32> value);
        partial void OnChildEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ObjectContextExampleModel", "FK_Entity_ChildEntity", "ChildEntity")]
        public ChildEntity ChildEntity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChildEntity>("ObjectContextExampleModel.FK_Entity_ChildEntity", "ChildEntity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChildEntity>("ObjectContextExampleModel.FK_Entity_ChildEntity", "ChildEntity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ChildEntity> ChildEntityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChildEntity>("ObjectContextExampleModel.FK_Entity_ChildEntity", "ChildEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ChildEntity>("ObjectContextExampleModel.FK_Entity_ChildEntity", "ChildEntity", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
